apiVersion: apps/v1
kind: Deployment
metadata:
  name: success-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: success-app
  template:
    metadata:
      labels:
        app: success-app
    spec:
      containers:
      - name: success-app
        image: ironjin92/my-registry:latest
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: my-registry